### ISSUE TITLE
Dask tasks start delayed with Batched Kafka

### ISSUE THREAD

**Issue by skmatti** [python-streamz/streamz#253] opened 2019-05-23 19:30 UTC
Dask tasks seem to get delayed slightly and the delay is propagated to subsequent batches when reading messages from Kafka in batches. 

The following Dask dashboard depicts this issue:
![image](https://user-images.githubusercontent.com/22752968/58280392-57308300-7d55-11e9-95d0-7a7eed1e7e71.png)

The batch interval I am using is 10 secs. Dask seems to finish reading messages well inside this time, but the start of the subsequent batch is delayed slightly. Whats worse, it is propagated to subsequent batches. I am not sure if this has to do with how FromKafkaBatched class is implemented or an issue with Kafka. 

It would be great if someone let me know about figuring out the root cause as I am fairly new to Asynchronous programming.

**Comment by mrocklin** [comment] 2019-05-23 19:35
If the problem is due to Dask then this document might help:
http://docs.dask.org/en/latest/phases-of-computation.html

It might also be just due to how Streamz handles Kafka things or a Streamz
bug.  I'm not sure.

**Comment by martindurant** [comment] 2019-05-23 19:35
I am not surprised: the implementation currently reads and emits, and then sleeps for (a minimum of) the poll time, not taking into account how long the processing took. A rigorous alternative might be
- to always set a new coroutine at the *start* of each loop
- to time how long the processing has taken and subtract it from the sleep statement (this is the smallest change), or
- have the inner part of the loop as its own coroutine, so an outer block just waits on it

**Comment by skmatti** [comment] 2019-05-23 21:39
What's interesting is this does not happen with all the pipelines or significant only in case of some pipelines. It would be interesting to know the reason behind this. May be Kafka's `get_watermark_offsets` method takes longer time when brokers are busy serving the consumers.

I am guessing the process time you are referring is the time taken to get the latest offsets and create batches. If it is then the easiest method to solve this is to capture this time and subtract as you mentioned above. But, would this be the best way?. Is this issue reasonable enough to make changes to current implementation of FromKafkaBatched?.

**Comment by martindurant** [comment] 2019-05-24 14:25
Would it be worth temporarily sprinkling the polling function with timestamped logging statements to figure out what is taking the time?

**Comment by skmatti** [comment] 2019-05-24 17:24
So, I added timestamps to compute the time taken to read offsets and create batches. This seems to take an average time of `~0.1 secs`(0.07-0.2). I subtracted this from sleep statement. But the tasks are still delayed (But, now it is slightly better than it was before).

**Comment by martindurant** [comment] 2019-05-24 17:48
Presumably there is also a pause at `yield _emit`, in which maybe several event loop ticks happen, depending on what is downstream

**Comment by skmatti** [comment] 2019-06-12 18:37
Sorry It took me some time to respond. I captured CPU times for each of `_emit` calls and deducted this from sleep command. But, there is no significant improvement as such if any.

**Comment by chinmaychandak** [comment] 2019-07-26 22:17
Just an update: This can be closed now, since the issue seems to be fixed with cudf v0.9.

**Closed** 2019-07-26 22:51 UTC
